# Generated by Django 4.1.3 on 2022-11-07 19:31
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100,
                                     verbose_name="Category Name"),
                ),
                (
                    "max_reward_points_encash",
                    models.IntegerField(
                        default=0, verbose_name="Max Reward Points Encash"),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_unit",
                    models.CharField(
                        choices=[("P", "Percentage"), ("A", "Amount")],
                        max_length=1,
                        verbose_name="Discount Unit",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True,
                                         verbose_name="Date Created"),
                ),
                (
                    "valid_unit",
                    models.CharField(choices=[("D", "Day")],
                                     max_length=1,
                                     verbose_name="Valid Unit"),
                ),
                ("valid_value",
                 models.IntegerField(verbose_name="Valid Value")),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Coupon Code",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2,
                                        max_digits=10,
                                        verbose_name="Discount Value"),
                ),
                (
                    "minimum_order_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimum Order Value",
                    ),
                ),
                (
                    "maximum_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Maximum Discount Amount",
                    ),
                ),
                (
                    "is_redeem_allowed",
                    models.BooleanField(default=False,
                                        verbose_name="Is Redeem Allowed"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
